# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d12de66ea7ec1d241628e128b0f336513c5da499b2ebc81ec735d2973d23ab688eb55d7c46ae3122d00a9d5cf52f7777353fe3ee21697f4f5462276fe42ca89

test:
  secret_key_base: 2a2e821a338a6b3b427d253989639f9a23aae3fda49a58d61d14f52b356329950732db8a33fe7328498a0c5698fcc4bc9af50b38c79541166ba57f98fad6b7ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
